### ISSUE TITLE
FAIL: test_magnetic

### ISSUE THREAD

**Issue by godofyoga** [jleinonen/pymiecoated#7]
FAIL: test_magnetic (pymiecoated.test.test_mie.MieTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yogesh/anaconda/lib/python2.7/site-packages/pymiecoated/test/test_mie.py", line 108, in test_magnetic
    self.assertLess(abs(S12_ref[0]-S12[0])/S12_ref[0], epsilon)
AssertionError: (4.4921206279178666e-14+5.3475134338212124e-15j) not less than 2.220446049250313e-14
Please help me to solve installation problem

**Comment by jleinonen** [comment]
Hi,

Thanks for the report. This is a bug in the testing code and I'll fix it in
a future revision. It should be safe to use the code regardless.

-Jussi

**Comment by jleinonen** [comment]
Fixed in 7ca9950.
